#TODO
debug ?= 1 #isključiti dodavanjem debug=0 pri make-u, npr. $ make debug=0 run

CFLAGS = 
LDFLAGS = -O3
LDLIBS =

datoteka.o: datoteka.c datoteka.h
	gcc $(CFLAGS) -o datoteka.o -c datoteka.c

brisi obrisi:
	rm -rf *.o *.d
