#TODO
debug ?= 1 #isključiti dodavanjem debug=0 pri make-u, npr. $ make debug=0 run

CFLAGS = 
LDFLAGS = -O3
LDLIBS =

dublje.o: dublje.c dublje.h
	gcc $(CFLAGS) -o dublje.o -c dublje.c

brisi obrisi:
	rm -rf *.o *.d
