#TODO
#TODO
debug ?= 1 #isključiti dodavanjem debug=0 pri make-u, npr. $ make debug=0 run

CFLAGS = 
LDFLAGS = -O3
LDLIBS =

pobroji.o: pobroji.c pobroji.h
	gcc $(CFLAGS) -o pobroji.o -c pobroji.c

brisi obrisi:
	rm -rf *.o *.d
